# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    container:
      image: codera/af-client_2018SP3-P2:1809
      credentials:
         username: codera
         password: ${{ secrets.DOCKERHUBTOKEN }}
    steps:  

    - name: What OS version is running
      run: powershell -c [System.Environment]::OSVersion.Version

         
       
